management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: WelcomeApi
  boot:
    admin:
      client:
        url: http://localhost:9191/

        msg: Welcome from yml file from gitHub Repo
